import Head from "next/head";
import Image from "next/image";
import Footer from "../components/Footer";
import Header from "../components/Header";
import HomePage from "../components/HomePage";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div className="p-0 px-8">
      <Header />
      <Head>
        <title>Zero 🚀</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <HomePage />
      <Footer />
    </div>
  );
}
